# alteração só pra testar uma coisa.

# -*- coding: utf-8 -*-
"""Exercicio 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dbmh3Qle2NMYMSeXfNxvNi5GoCQxmp_V

# Nova seção

**TIFFFLE - para leitura do dado raster**

**MATPLOTLIB - para visualização da imagem (multibanda)**
"""

import tifffile as tif
import matplotlib.pyplot as plt

img = tif.imread('/content/L71221071_07120010720_DN.tif')

img.shape

plt.imshow(img[:,:,2], cmap = 'Greys_r') # O PLT não consegue entender imagem multibanda. Por isso, selecionou a banda 1 para visualizar.

"""# Nova seção

Bibliotecas não nativas do COLAB
"""

# Não nativas são as: SPECTRAL, GDAL e RASTERIO

!pip install GDAL
!pip install RASTERIO
!pip install spectral

# SPECTRAL é uma biblioteca capaz realizar a composição colorida de imagens
# através do método IMSHOW (diferente do plt.imshow)

from spectral import imshow

img = tif.imread('/content/L71221071_07120010720_DN.tif')

imshow(img) #O SPECTRAL gera composições coloridas aleatórias, caso não dê parâmetros

imshow(img, bands=(4,2,1))



"""# FORMA 1

TIFFFLE, MATPLOTLIB e SPECTRAL

"""

import tifffile as tif
import matplotlib.pyplot as plt
! pip install spectral

from spectral import imshow

img = tif.imread('/content/L71221071_07120010720_DN.tif')

img.shape

plt.imshow(img[:, :, 5], cmap= 'Greys_r')

imshow(img, (3,2,1))



"""# FORMA 2"""

!pip install gdal
import numpy as np

from osgeo import gdal

img2 = gdal.Open('/content/L71221071_07120010720_DN.tif')

# É preciso converter para Array.
# Forma 1 - Criar uma nova variável (img3) e atribuir o img2.readasarray

img3 = img2.ReadAsArray()

img3 = img3.swapaxes(0,1)

img3.shape

imshow(img3, (3,2,1))

"""Forma 2 - Converter as bandas separadamente (.getreasterband().readasarray())
e depois empilhar (.dstack([bandas]))
"""

b1 = img2.GetRasterBand(1).ReadAsArray()
b2 = img2.GetRasterBand(2).ReadAsArray()
b4 = img2.GetRasterBand(4).ReadAsArray()

stack = np.dstack([b1,b2,b4])
stack.shape

imshow(stack, (1,2,0))

"""**Forma 3 - RASTERIO**"""

!pip install rasterio

import rasterio
from rasterio.plot import show

img4 = rasterio.open('/content/L71221071_07120010720_DN.tif')

img4.shape

# para transformar em numpy.array é semelhante ao GDAL
# porém, utiliza o próprio método da RASTERIO: .read()

b1 = rst.read(1)
b2 = rst.read(2)
b4 = rst.read(4)

stack = np.stack ([b1,b2,b4])

show(stack, (2,1,0))

rst.shape



"""# RASTERIO"""

!pip install rasterio

import rasterio
from rasterio.plot import show

rst = rasterio.open('/content/L71221071_07120010720_DN.tif')

rst.shape

show(rst, cmap=('Greys_r'))

b1 = rst.read(1)
b2 = rst.read(2)
b4 = rst.read(4)

stack = np.dstack([b1,b2,b4])

stack.shape

imshow(stack, (1,2,0))

# fim de código
